name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Git
        run: |
          git config --global user.name "avchugaev"
          git config --global user.email "achugaev93@gmail.com"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run nx -- affected --target=lint --base=last-release

      - name: Test
        run: npm run nx -- affected --target=test --base=last-release

      - name: Build
        run: npm run nx -- affected --target=build --base=last-release

      - name: Version
        run: npm run nx -- affected --target=version --base=last-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag last-release
        run: git tag -f last-release

      - name: Tag last-release
        run: git push origin last-release --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
